[project]
name = "chimege-tts"
version = "0.1.0"
description = "Text to speech synthesis for Mongolian language"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.4",
]
